// Code generated by MockGen. DO NOT EDIT.
// Source: usecases/auth/repository.go

// Package mock_auth is a generated GoMock package.
package mock_auth

import (
	domain "api/domain"
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// VerifyFirebaseToken mocks base method
func (m *MockRepository) VerifyFirebaseToken(ctx context.Context, token string) (domain.Auth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyFirebaseToken", ctx, token)
	ret0, _ := ret[0].(domain.Auth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyFirebaseToken indicates an expected call of VerifyFirebaseToken
func (mr *MockRepositoryMockRecorder) VerifyFirebaseToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyFirebaseToken", reflect.TypeOf((*MockRepository)(nil).VerifyFirebaseToken), ctx, token)
}
